version: '3'

services:
  web:
    build:
      context: nginx
      dockerfile: Dockerfile
    image: acrsoldout.azurecr.io/web
    ports:
      - "80:80"
    volumes:
      - ./source:/source
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  php:
    build:
      context: php
      dockerfile: Dockerfile
    image: acrsoldout.azurecr.io/php
    ports:
      - "9000"
    volumes:
      - ./source:/source
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./logs/php:/var/log/php7
